#!/bin/csh -fx

\rm -rf work
\rm test_bus_protocol_check1.log

#=======================================
# C R E A T E / S E T  'work' lib
#--------------------------------
vlib work

#=======================================
# C O M P I L E
#---------------
vlog -sv test_bus_protocol.sv bus_protocol.v bus_protocol_property.sv +acc +cover +define+check1
                                    
#=======================================
# S I M
#------
vsim -assertdebug -coverage -c test_bus_protocol -l test_bus_protocol_check1.log -do " run -all; quit" 
