#!/bin/csh -fx
\rm -rf work
\rm test_fifo_check2.log

#=======================================
# C R E A T E / S E T  'work' lib
#--------------------------------
vlib work

#--------------------------------------------------
# To compile with bug in RTL that is caught by CHECK # 2
# CHECK # 2. Check that fifo_empty is asserted the same clock that fifo 'cnt' is 0.
# Disable this property 'iff (!rst)'
#--------------------------------------------------
vlog -sv fifo.v fifo_property.sv test_fifo.sv +define+check2

#--------------------------------------------------
#To Simulate 
#--------------------------------------------------
vsim -assertdebug -coverage -c test_fifo -l test_fifo_check2.log -do " run -all; quit"
